import type {Metadata} from "next";
import "./globals.css";
import {Inter} from "next/font/google";
import Header from "@/components/Header/Header";

// Carregar a fonte com suporte completo (peso, subset, etc.)
const inter = Inter({
    subsets: ["latin"],
    display: "swap", // carrega de forma suave
    variable: "--font-inter", // define uma CSS variable
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
        <body className={inter.variable} style={{backgroundColor: 'var(--brand-background-100)'}}>
        <div>
            <Header/>
        </div>
        {children}
        </body>
        </html>
    );
}
